### ISSUE TITLE
DOI checker stripping valid characters 

### ISSUE THREAD

**Issue by scottshambaugh** [openjournals/buffy#71]
In the check [here](https://github.com/scipy-conference/scipy_proceedings/pull/711#issuecomment-1172559212), the doi checker is stripping out the parentheses from DOI [10.1016/0041-5553(67)90144-9](https://doi.org/10.1016/0041-5553(67)90144-9) and [10.1016/S0378-4754(00)00270-6](https://doi.org/10.1016/S0378-4754(00)00270-6), and erroneously labeling them as invalid. 

I don't know ruby like, at all, but I believe the offending line is here: https://github.com/openjournals/buffy/blob/ca0ef58f15bb926a6abea2a3c0ba93d7b4e75225/app/lib/doi_checker.rb#L48

From https://www.doi.org/syntax.html :

> * There are no character restrictions for DOI schemes per se.
> * When DOIs are embedded in URLs, they must follow the URL syntax conventions, but the same DOIs need not follow those conventions in other contexts, e.g., inventory databases.
> * The percent character (%) must always be hex encoded (%25) in any web form, batch input, or URL. Other excluded characters must always be hex encoded in URLs, but may be entered either raw or hex encoded in web forms and batch jobs.

Considering that the DOI checker looks at the URL explicitly, I think the only thing that should be stripped out from the string is leading and trailing spaces.

**Comment by xuanxu** [comment]
Hey @scottshambaugh thanks for reporting the issue. The line you highlighted is actually the fix for the error. 
The origin of the error is that scipy-conference's fork is not up to date with upstream. 

Here is currently the same line in the scipy-conference fork: 
https://github.com/scipy-conference/buffy/blob/scipy/app/lib/doi_checker.rb#L38

I've opened [an issue there](https://github.com/scipy-conference/buffy/issues/3).

**Comment by mepa** [comment]
Thanks, @scottshambaugh and @xuanxu, for noticing this and opening an issue in the fork.
